[package]
name = "mrtx"
version = "0.1.0"
authors = ["darksv <darek969-12@o2.pl>"]
edition = "2018"

[dependencies]
rand = "0.7.0-pre.1"
rayon = "1.0.3"
wavefront_obj = "6.0.0"

[profile.release]
debug = true